<a href="https://colab.research.google.com/github/KeerthanaSistla/Python-for-Data-Analysis-Visualization/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [ ]:
import numpy as np

In [ ]:
list1 = [1,2,3,4,5]
x = np.array(list1)
print(x)
print(type(x))
print(np.shape(x))
print(x.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
(5,)


In [ ]:
print(type(np.array([2,2,2,2])))
print(type(np.array((3,3,3,3))))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
print(np.array({1,1,1,1}).shape)

()


2D Arrays

In [ ]:
arr2d = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(arr2d)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
arr2d_2 = np.array([list1,list2])
print(arr2d_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(arr2d_2.shape)

(2, 5)


Datatype Objects

In [ ]:
print(np.longdouble(100)/np.longdouble(3))
print(np.array([1,2,3.1453,5],dtype='g'))

33.333333333333333332
[1.     2.     3.1453 5.    ]


Slicing and Indexing

In [ ]:
array_1d = np.array([2,5,6,7,6,4,3])
array_2d = np.array([[2,5,6,7,60,47,3],[11,50,6,9,62,42,30],[16,53,86,69,2,2,50]])
print(array_1d)

[2 5 6 7 6 4 3]


In [ ]:
print(array_1d[4])
print(array_1d[4:])
print(array_1d[1:6])
print(array_1d[::-1])

6
[6 4 3]
[5 6 7 6 4]
[3 4 6 7 6 5 2]


In [ ]:
print(array_2d)
print(array_2d[1:,2:])
print(array_2d[2,6])
print(array_2d[::-1,])
print(array_2d[::-1,])

[[ 2  5  6  7 60 47  3]
 [11 50  6  9 62 42 30]
 [16 53 86 69  2  2 50]]
[[ 6  9 62 42 30]
 [86 69  2  2 50]]
50
[[16 53 86 69  2  2 50]
 [11 50  6  9 62 42 30]
 [ 2  5  6  7 60 47  3]]
[[16 53 86 69  2  2 50]
 [11 50  6  9 62 42 30]
 [ 2  5  6  7 60 47  3]]


Boolean Masking

In [ ]:
print(array_1d)
print(array_1d>3)
print(array_1d[array_1d>3])

[2 5 6 7 6 4 3]
[False  True  True  True  True  True False]
[5 6 7 6 4]


In [ ]:
print(array_2d)
print(array_2d>10)
print(array_2d[array_2d>10])

[[ 2  5  6  7 60 47  3]
 [11 50  6  9 62 42 30]
 [16 53 86 69  2  2 50]]
[[False False False False  True  True False]
 [ True  True False False  True  True  True]
 [ True  True  True  True False False  True]]
[60 47 11 50 62 42 30 16 53 86 69 50]


Shape of Array

In [ ]:
print(array_2d[array_2d>10].shape)
print(array_2d[array_2d>10].reshape(2,6))

(12,)
[[60 47 11 50 62 42]
 [30 16 53 86 69 50]]


In [ ]:
array_1 = np.array([1,2,3,4,5,6,4,2,2,1])
print(array_1)
np.reshape(array_1,(2,5))
print(array_1)
array_1.flatten().shape
print(array_1)

[1 2 3 4 5 6 4 2 2 1]
[1 2 3 4 5 6 4 2 2 1]
[1 2 3 4 5 6 4 2 2 1]


In [ ]:
array_2 = np.array([[2,3,2,4,6],[5,6,3,2,4]])
print(array_2)
print(np.ravel(array_2))

[[2 3 2 4 6]
 [5 6 3 2 4]]
[2 3 2 4 6 5 6 3 2 4]


Concatinate

In [ ]:
array_1 = np.array([[1, 1, 1], [2, 2, 2]])
array_2 = np.array([[3, 3, 3],[4, 4, 4],[5, 5, 5]])
array_3 = np.array([[3, 3],[4, 4],[5, 5]])
array_4 = np.concatenate((array_1,array_2),axis=0)
print(array_4)
array_5 = np.concatenate((array_3,array_2),axis=1)
print(array_5)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]
[[3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


Transpose Array

In [ ]:
print(array_1)
print(np.transpose(array_1))

[[1 1 1]
 [2 2 2]]
[[1 2]
 [1 2]
 [1 2]]


Sorting Elements

In [ ]:
array_unsort = np.array([[1,10,3],[2,3,1]])
print(array_unsort)
print(np.sort(array_unsort))
print(np.sort(array_unsort,axis=1))
print(np.sort(array_unsort,axis=0))

[[ 1 10  3]
 [ 2  3  1]]
[[ 1  3 10]
 [ 1  2  3]]
[[ 1  3 10]
 [ 1  2  3]]
[[ 1  3  1]
 [ 2 10  3]]


Array Arithmatic (Broadcasting)

In [ ]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([5, 6, 7])
array_3 = np.array([[1, 2, 3, 4, 5], [5, 3, 2, 4, 2], [1, 2, 3, 4, 5]])

In [ ]:
print(array_1+array_2)
print(np.add(array_1,array_2))
print(array_1-array_2)
print(np.subtract(array_1,array_2))

[ 6  8 10]
[ 6  8 10]
[-4 -4 -4]
[-4 -4 -4]


In [ ]:
print(array_1+5)
print(array_1-5)
print(array_1*5)
print(array_1/5)

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]


Sum of elements

In [ ]:
print(array_3)
print(sum(array_3))

[[1 2 3 4 5]
 [5 3 2 4 2]
 [1 2 3 4 5]]
[ 7  7  8 12 12]


Cumilative Sum of Elements in an Axis

In [ ]:
print(np.cumsum(array_3))
print(np.cumsum(array_3, axis=0))
print(np.cumsum(array_3, axis=1))

[ 1  3  6 10 15 20 23 25 29 31 32 34 37 41 46]
[[ 1  2  3  4  5]
 [ 6  5  5  8  7]
 [ 7  7  8 12 12]]
[[ 1  3  6 10 15]
 [ 5  8 10 14 16]
 [ 1  3  6 10 15]]


Arg Max/Min - Max/Min in given axis

In [ ]:
print(np.amax(array_3, axis=0))
print(np.amin(array_3, axis=0))

[5 3 3 4 5]
[1 2 2 4 2]


Average of elements in given axis

In [ ]:
print(np.mean(array_3, axis=0))

[2.33333333 2.33333333 2.66666667 4.         4.        ]


Using External Database

In [ ]:
x = np.loadtxt("tfl-daily-cycle-hires.txt",delimiter=',',usecols=(1),skiprows=1)
print("Number of Zeros:", np.count_nonzero(x))
print("Max:", x.max())
print("Min:", x.min())
print("Mean:", x.mean())
print("Std:", x.std())

Number of Zeros: 4081
Max: 73094.0
Min: 2764.0
Mean: 26261.932124479295
Std: 9740.107235227775
