<a href="https://colab.research.google.com/github/KeerthanaSistla/Python-for-Data-Analysis-Visualization/blob/main/Python_for_Data_Analysis_%26_Visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Python

In [ ]:
a = 16
b = 3

print("Sum (a+b) =", a+b)
print("Difference (a-b) =", a-b)
print("Absolute Difference (abs(a-b)) =", abs(a-b))
print("Product (a*b) =", a*b)
print("Floor Division (a//b) =", a//b)
print("Quotient (round(a/b, 4)) =", round(a/b, 4))
print("Reminder (a%b) =", a%b)
print("Exponent (a**b) =", a**b)

x = input("Enter two numbers: ")
y = input()
print(f'x is {x}, y is {y}')
print("x==y:", x==y)
print("x!=y:", x!=y)

Sum (a+b) = 19
Difference (a-b) = 13
Absolute Difference (abs(a-b)) = 13
Product (a*b) = 48
Floor Division (a//b) = 5
Quotient (round(a/b, 4)) = 5.3333
Reminder (a%b) = 1
Exponent (a**b) = 4096
Enter two numbers: 

x is , y is 
x==y: True
x!=y: False


#Strings

In [ ]:
str = "This Is A String"
s2 = "This is a string \nwritten in two lines"

print(str)
print(s2)

print(str[:4:])
print(str[6:])
print(str[::3])
print(str[::-1])
print(str[13:2:-2])

This Is A String
This is a string 
written in two lines
This
s A String
Tss rg
gnirtS A sI sihT
it  Is


Methods and Properties

In [ ]:
print(str.upper())
print(str.lower())

a = "Red Flag"
print("'a' is", a)
a.replace("Red", "Green")
print("'a' changed to", a)

b = "THIS, IS A, STRING !!!"
print("'b' is", b)
print(b.split())
print(b.split(","))
print(b.split("!"))

THIS IS A STRING
this is a string
'a' is Red Flag
'a' changed to Red Flag
'b' is THIS, IS A, STRING !!!
['THIS,', 'IS', 'A,', 'STRING', '!!!']
['THIS', ' IS A', ' STRING !!!']
['THIS, IS A, STRING ', '', '', '']


Concatination

In [ ]:
print("Concatination of strings 'a' and 'b'")
print(a + "... " + b)

Concatination of strings 'a' and 'b'
Red Flag... THIS, IS A, STRING !!!


String formatting

In [ ]:
name = "Keerthana"
greet = f"Hi, my name is {name}"
print(greet)

Hi, my name is Keerthana


#Lists

In [ ]:
list_1 = [2,17,18,19,20]
list_2 = ["Keerthana", 21, "Sistla", 101]
list_3 = ["XYZ", ["ABC", 7], [1, "PQR", 0.5]]

List Indexing

In [ ]:
print(list_1)
print(list_1[3])
print(list_1[-3])
print(list_1[:3:2])
print(list_1[2:5])

[2, 17, 18, 19, 20]
19
18
[2, 18]
[18, 19, 20]


Element Type

In [ ]:
print(list_2)
print(type(list_2))
print(type(list_2[2]))
list_2[2] = 15
print(list_2)
print(list_2[2])
print(type(list_2[2]))

['Keerthana', 21, 'Sistla', 101]
<class 'list'>
<class 'str'>
['Keerthana', 21, 15, 101]
15
<class 'int'>


List Mutability

In [ ]:
print(list_3)
print(list_3[2][1])
list_3[2][1]=13
print(list_3[2][1])
print(list_3)

['XYZ', ['ABC', 7], [1, 'PQR', 0.5]]
PQR
13
['XYZ', ['ABC', 7], [1, 13, 0.5]]


Methods

In [ ]:
list_1.append(list_2)
print(list_1)
list_1.extend(list_2)
print(list_1)

[2, 17, 18, 19, 20, ['Keerthana', 21, 15, 101]]
[2, 17, 18, 19, 20, ['Keerthana', 21, 15, 101], 'Keerthana', 21, 15, 101]


In [ ]:
list_1.insert(2, 1000)
print(list_1)

[2, 17, 1000, 18, 19, 20, ['Keerthana', 21, 15, 101], 'Keerthana', 21, 15, 101]


In [ ]:
list_1.remove(20)
print(list_1)
removed_item = list_1.pop()
print(removed_item)
print(type(removed_item))

[2, 17, 1000, 18, 19, ['Keerthana', 21, 15, 101], 'Keerthana', 21, 15, 101]
101
<class 'int'>


In [ ]:
list_1 = [2, 17, 1000, 18, 19, 21, 15]

In [ ]:
print("Len:", len(list_1))
print("Max:", max(list_1))
print("Min:", min(list_1))

Len: 7
Max: 1000
Min: 2


#Dictionaries

In [ ]:
dict_1 = {'Brand':'Ford', "Cost":25000}
print(dict_1)

{'Brand': 'Ford', 'Cost': 25000}


In [ ]:
print(dict_1['Brand'])

Ford


In [ ]:
dict_1['Brand']="Audi"
print(dict_1['Brand'])
print(dict_1)

Audi
{'Brand': 'Audi', 'Cost': 25000}


In [ ]:
dict_1['Transmission']='Manual'
print(dict_1)

{'Brand': 'Audi', 'Cost': 25000, 'Transmission': 'Manual'}


In [ ]:
dict_1['other_attributes'] = {'color':'Black', 'year':2021}
print(dict_1)
print(dict_1['other_attributes']['year'])

{'Brand': 'Audi', 'Cost': 25000, 'Transmission': 'Manual', 'other_attributes': {'color': 'Black', 'year': 2021}}
2021


In [ ]:
dict_1['previous_owners']=['Mike', 'Shelly', 'Nitin']
print(dict_1)

{'Brand': 'Audi', 'Cost': 25000, 'Transmission': 'Manual', 'other_attributes': {'color': 'Black', 'year': 2021}, 'previous_owners': ['Mike', 'Shelly', 'Nitin']}


In [ ]:
p = dict_1.pop('previous_owners')
print(p)
print(dict_1)

['Mike', 'Shelly', 'Nitin']
{'Brand': 'Audi', 'Cost': 25000, 'Transmission': 'Manual', 'other_attributes': {'color': 'Black', 'year': 2021}}


In [ ]:
print("Items: ", dict_1.items())
print("Keys: ", dict_1.keys())
print("Values: ", dict_1.values())

Items:  dict_items([('Brand', 'Audi'), ('Cost', 25000), ('Transmission', 'Manual'), ('other_attributes', {'color': 'Black', 'year': 2021})])
Keys:  dict_keys(['Brand', 'Cost', 'Transmission', 'other_attributes'])
Values:  dict_values(['Audi', 25000, 'Manual', {'color': 'Black', 'year': 2021}])


#Tuples

In [ ]:
x = (1,2,2,3)
print(x)
type(x)

(1, 2, 2, 3)


tuple

In [ ]:
y = (1,'John',[1,2,3],{'key1','value1'})
print(y)
print(y[1])

(1, 'John', [1, 2, 3], {'key1', 'value1'})
John


In [ ]:
z = (1,1,1,1,1,1,1,2,2,2,2,3,3,3,3,3)
print(z.count(1))
print(z.index(3))

7
11


#Sets

In [ ]:
x=set()
x={1,3,5}
print(x)
print(type(x))

{1, 3, 5}
<class 'set'>


In [ ]:
x.add("xyz")
x.add(4)
print(x)


{1, 3, 4, 5, 'xyz'}


In [ ]:
list_1=[1,2,2,3]
set_1=set(list_1)
print(set_1)

{1, 2, 3}


In [ ]:
y={1,2,3,4}
z={3,4,5,6}
print(y.intersection(z))
print(y.union(z))

{3, 4}
{1, 2, 3, 4, 5, 6}


#Conditional Statements

In [ ]:
if 4<3:
    print("The condition is True")
print("This statement will always print")

This statement will always print


In [ ]:
from random import randint
x = randint(1, 300)
print(x)
if x<200:
    print("x is less than 200")
    if x>100:
        print("x lies between 100 and 200")
elif x==200:
    print("x is equal to 200")
else:
    print("x is greater than 200")

256
x is greater than 200


#Loops

In [ ]:
for _ in range(5):
    print("I love Python")

I love Python
I love Python
I love Python
I love Python
I love Python


In [ ]:
for i in range(10, 50, 3):
    print(i)

10
13
16
19
22
25
28
31
34
37
40
43
46
49


In [ ]:
sample=[11,2,41,7,25]
for ele in sample:
    print("Element:", ele)
    print("Square:", ele**2)

Element: 11
Square: 121
Element: 2
Square: 4
Element: 41
Square: 1681
Element: 7
Square: 49
Element: 25
Square: 625


In [ ]:
x = [[1,2],[3,4],[7,9]]
for i in x:
    print(i[0])
    print(i[1])

1
2
3
4
7
9


In [ ]:
x = [[1,2],[3,4],[7,9]]
for a,b in x:
    print(a)
    print(b)

1
2
3
4
7
9


In [ ]:
dict_1 = {'key_1':'value_1','key_2':'value_2'}
for x in dict_1:
    print(x)

key_1
key_2


In [ ]:
for k,v in dict_1.items():
    print("Key", k, "\tValue", v)

Key key_1 	Value value_1
Key key_2 	Value value_2


In [ ]:
x=10
while x>0:
    print(x)
    x-=1

10
9
8
7
6
5
4
3
2
1


#Functions

In [ ]:
def welcome_message():
    print("Welcome")
welcome_message()

Welcome


In [ ]:
def welcome(name):
    print(f"Welcome {name}")
welcome("Keerthana")

Welcome Keerthana


In [ ]:
def welcome(name1, name2, name3):
    print(f"Welcome {name1}, {name2} and {name3}")
welcome('A', 'B', 'C')

Welcome A, B and C


In [ ]:
def welcome(firstName, lastName):
    return f"Welcome {firstName} {lastName}"
print(welcome("Keerthana", "Sistla"))

Welcome Keerthana Sistla


In [ ]:
def greater_than_10(x):
    for ele in x:
        if ele > 10:
            print("True")
        else:
            print("False")

greater_than_10([1, 32, 10])

False
True
False


In [ ]:
def sum(l):
    s = 0
    for ele in l:
        s += ele
    return s

def avg(l):
    total = sum(l)
    length = len(l)
    return total / length

print(avg([1, 2, 3, 4, 5]))

3.0


In [ ]:
def my_func(*args):
    print(type(args))
    return args

print(my_func(1,2,3))

<class 'tuple'>
(1, 2, 3)


In [ ]:
def key_word_func(**kwargs):
    print(type(kwargs))
    return kwargs

print(key_word_func(name="K", age=21))

<class 'dict'>
{'name': 'K', 'age': 21}


In [ ]:
def args_kwargs(*args, **kwargs):
    print(args)
    print(kwargs)

args_kwargs(1,2,3,4,"random_string",sport="football",age=33)

(1, 2, 3, 4, 'random_string')
{'sport': 'football', 'age': 33}


Map function

In [ ]:
countries_list = ['Argentina', "United Stats", "Germany"]

for x in countries_list:
    print(len(x))

print(list(map(len, countries_list)))

9
12
7
[9, 12, 7]


In [ ]:
def return_len(x):
    return f"{x}: {len(x)}"

print(return_len('Hello'))

print(list(map(return_len, countries_list)))

Hello: 5
['Argentina: 9', 'United Stats: 12', 'Germany: 7']


Filter Method

In [ ]:
countries_list = ['Argentina', 10, "Mexico", 18, "Brazil"]

def is_str(x):
    return type(x)==str

print(list(filter(is_str, countries_list)))
print(list(map(is_str, countries_list)))

['Argentina', 'Mexico', 'Brazil']
[True, False, True, False, True]


Lambda Function

In [ ]:
print(lambda x: type(x)==str)
print(list(filter(lambda x: type(x)!=str, countries_list)))

<function <lambda> at 0x7f4ae3f11d00>
[10, 18]


In [ ]:
lst = [1,2,3,4,5]
sq = list(map(lambda x: x**2, lst))
print(sq)

[1, 4, 9, 16, 25]


#Numpy

In [ ]:
import numpy as np

In [ ]:
list1 = [1,2,3,4,5]
x = np.array(list1)
print(x)
print(type(x))
print(np.shape(x))
print(x.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
(5,)


In [ ]:
print(type(np.array([2,2,2,2])))
print(type(np.array((3,3,3,3))))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
print(np.array({1,1,1,1}).shape)

()


2D Arrays

In [ ]:
arr2d = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(arr2d)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
arr2d_2 = np.array([list1,list2])
print(arr2d_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(arr2d_2.shape)

(2, 5)


Datatype Objects

In [ ]:
print(np.longdouble(100)/np.longdouble(3))
print(np.array([1,2,3.1453,5],dtype='g'))

33.333333333333333332
[1.     2.     3.1453 5.    ]


Slicing and Indexing

In [ ]:
array_1d = np.array([2,5,6,7,6,4,3])
array_2d = np.array([[2,5,6,7,60,47,3],[11,50,6,9,62,42,30],[16,53,86,69,2,2,50]])
print(array_1d)

[2 5 6 7 6 4 3]


In [ ]:
print(array_1d[4])
print(array_1d[4:])
print(array_1d[1:6])
print(array_1d[::-1])

6
[6 4 3]
[5 6 7 6 4]
[3 4 6 7 6 5 2]


In [ ]:
print(array_2d)
print(array_2d[1:,2:])
print(array_2d[2,6])
print(array_2d[::-1,])
print(array_2d[::-1,])

[[ 2  5  6  7 60 47  3]
 [11 50  6  9 62 42 30]
 [16 53 86 69  2  2 50]]
[[ 6  9 62 42 30]
 [86 69  2  2 50]]
50
[[16 53 86 69  2  2 50]
 [11 50  6  9 62 42 30]
 [ 2  5  6  7 60 47  3]]
[[16 53 86 69  2  2 50]
 [11 50  6  9 62 42 30]
 [ 2  5  6  7 60 47  3]]


Boolean Masking

In [ ]:
print(array_1d)
print(array_1d>3)
print(array_1d[array_1d>3])

[2 5 6 7 6 4 3]
[False  True  True  True  True  True False]
[5 6 7 6 4]


In [ ]:
print(array_2d)
print(array_2d>10)
print(array_2d[array_2d>10])

[[ 2  5  6  7 60 47  3]
 [11 50  6  9 62 42 30]
 [16 53 86 69  2  2 50]]
[[False False False False  True  True False]
 [ True  True False False  True  True  True]
 [ True  True  True  True False False  True]]
[60 47 11 50 62 42 30 16 53 86 69 50]


Shape of Array

In [ ]:
print(array_2d[array_2d>10].shape)
print(array_2d[array_2d>10].reshape(2,6))

(12,)
[[60 47 11 50 62 42]
 [30 16 53 86 69 50]]


In [ ]:
array_1 = np.array([1,2,3,4,5,6,4,2,2,1])
print(array_1)
np.reshape(array_1,(2,5))
print(array_1)
array_1.flatten().shape
print(array_1)

[1 2 3 4 5 6 4 2 2 1]
[1 2 3 4 5 6 4 2 2 1]
[1 2 3 4 5 6 4 2 2 1]


In [ ]:
array_2 = np.array([[2,3,2,4,6],[5,6,3,2,4]])
print(array_2)
print(np.ravel(array_2))

[[2 3 2 4 6]
 [5 6 3 2 4]]
[2 3 2 4 6 5 6 3 2 4]


Concatinate

In [ ]:
array_1 = np.array([[1, 1, 1], [2, 2, 2]])
array_2 = np.array([[3, 3, 3],[4, 4, 4],[5, 5, 5]])
array_3 = np.array([[3, 3],[4, 4],[5, 5]])
array_4 = np.concatenate((array_1,array_2),axis=0)
print(array_4)
array_5 = np.concatenate((array_3,array_2),axis=1)
print(array_5)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]
[[3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


Transpose Array

In [ ]:
print(array_1)
print(np.transpose(array_1))

[[1 1 1]
 [2 2 2]]
[[1 2]
 [1 2]
 [1 2]]


Sorting Elements

In [ ]:
array_unsort = np.array([[1,10,3],[2,3,1]])
print(array_unsort)
print(np.sort(array_unsort))
print(np.sort(array_unsort,axis=1))
print(np.sort(array_unsort,axis=0))

[[ 1 10  3]
 [ 2  3  1]]
[[ 1  3 10]
 [ 1  2  3]]
[[ 1  3 10]
 [ 1  2  3]]
[[ 1  3  1]
 [ 2 10  3]]


Array Arithmatic (Broadcasting)

In [ ]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([5, 6, 7])
array_3 = np.array([[1, 2, 3, 4, 5], [5, 3, 2, 4, 2], [1, 2, 3, 4, 5]])

In [ ]:
print(array_1+array_2)
print(np.add(array_1,array_2))
print(array_1-array_2)
print(np.subtract(array_1,array_2))

[ 6  8 10]
[ 6  8 10]
[-4 -4 -4]
[-4 -4 -4]


In [ ]:
print(array_1+5)
print(array_1-5)
print(array_1*5)
print(array_1/5)

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]


Sum of elements

In [ ]:
print(array_3)
print(sum(array_3))

[[1 2 3 4 5]
 [5 3 2 4 2]
 [1 2 3 4 5]]
[ 7  7  8 12 12]


Cumilative Sum of Elements in an Axis

In [ ]:
print(np.cumsum(array_3))
print(np.cumsum(array_3, axis=0))
print(np.cumsum(array_3, axis=1))

[ 1  3  6 10 15 20 23 25 29 31 32 34 37 41 46]
[[ 1  2  3  4  5]
 [ 6  5  5  8  7]
 [ 7  7  8 12 12]]
[[ 1  3  6 10 15]
 [ 5  8 10 14 16]
 [ 1  3  6 10 15]]


Arg Max/Min - Max/Min in given axis

In [ ]:
print(np.amax(array_3, axis=0))
print(np.amin(array_3, axis=0))

[5 3 3 4 5]
[1 2 2 4 2]


Average of elements in given axis

In [ ]:
print(np.mean(array_3, axis=0))

[2.33333333 2.33333333 2.66666667 4.         4.        ]


Using External Database

In [ ]:
x = np.loadtxt("tfl-daily-cycle-hires.txt",delimiter=',',usecols=(1),skiprows=1)
print("Number of Zeros:", np.count_nonzero(x))
print("Max:", x.max())
print("Min:", x.min())
print("Mean:", x.mean())
print("Std:", x.std())

Number of Zeros: 4081
Max: 73094.0
Min: 2764.0
Mean: 26261.932124479295
Std: 9740.107235227775


#Pandas

In [ ]:
import pandas as pd

In [ ]:
countries_table = pd.read_csv('top_10_countries.csv')
print(countries_table)

   Rank Country / Dependency    Region     Population % of world       Date
0     1                China      Asia  1,412,600,000     17.80%  31-Dec-21
1     2                India      Asia  1,386,946,912     17.50%  18-Jan-22
2     3        United States  Americas    333,073,186      4.20%  18-Jan-22
3     4         Indonesia[b]      Asia    271,350,000      3.42%  31-Dec-20
4     5             Pakistan      Asia    225,200,000      2.84%  01-Jul-21
5     6               Brazil  Americas    214,231,641      2.70%  18-Jan-22
6     7              Nigeria    Africa    211,401,000      2.67%  01-Jul-21
7     8           Bangladesh      Asia    172,062,576      2.17%  18-Jan-22
8     9            Russia[b]    Europe    146,171,015      1.84%  01-Jan-21
9    10               Mexico  Americas    126,014,024      1.59%  02-Mar-20


In [ ]:
print(type(countries_table))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
countries_table = pd.read_csv('top_10_countries_no_header.csv', header=None)
print(countries_table)

    0               1         2              3       4          5
0   1           China      Asia  1,412,600,000  17.80%  31-Dec-21
1   2           India      Asia  1,386,946,912  17.50%  18-Jan-22
2   3   United States  Americas    333,073,186   4.20%  18-Jan-22
3   4    Indonesia[b]      Asia    271,350,000   3.42%  31-Dec-20
4   5        Pakistan      Asia    225,200,000   2.84%  01-Jul-21
5   6          Brazil  Americas    214,231,641   2.70%  18-Jan-22
6   7         Nigeria    Africa    211,401,000   2.67%  01-Jul-21
7   8      Bangladesh      Asia    172,062,576   2.17%  18-Jan-22
8   9       Russia[b]    Europe    146,171,015   1.84%  01-Jan-21
9  10          Mexico  Americas    126,014,024   1.59%  02-Mar-20


Is in

In [ ]:
countries_data = pd.read_csv('top_10_countries.csv')
print(countries_data)
print(countries_data['Region'].isin(['Asia','Americas']))
print(countries_data[countries_data['Region'].isin(['Asia','Americas'])])
print(countries_data[~countries_data['Region'].isin(['Asia','Americas'])])

   Rank Country / Dependency    Region     Population % of world       Date
0     1                China      Asia  1,412,600,000     17.80%  31-Dec-21
1     2                India      Asia  1,386,946,912     17.50%  18-Jan-22
2     3        United States  Americas    333,073,186      4.20%  18-Jan-22
3     4         Indonesia[b]      Asia    271,350,000      3.42%  31-Dec-20
4     5             Pakistan      Asia    225,200,000      2.84%  01-Jul-21
5     6               Brazil  Americas    214,231,641      2.70%  18-Jan-22
6     7              Nigeria    Africa    211,401,000      2.67%  01-Jul-21
7     8           Bangladesh      Asia    172,062,576      2.17%  18-Jan-22
8     9            Russia[b]    Europe    146,171,015      1.84%  01-Jan-21
9    10               Mexico  Americas    126,014,024      1.59%  02-Mar-20
0     True
1     True
2     True
3     True
4     True
5     True
6    False
7     True
8    False
9     True
Name: Region, dtype: bool
   Rank Country / Dependency

Pandas Series

In [ ]:
index_list = [0,1,2,3,4,5]
data_list = [100,200,300,400,500,600]

In [ ]:
series_1 = pd.Series(data=data_list,index=index_list)
print(series_1)
print(series_1[3])

0    100
1    200
2    300
3    400
4    500
5    600
dtype: int64
400


In [ ]:
month_index_2021 = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
revenue_data_2021 = (212861,100372,128953,100163,208129,182944,236284,243133,198641,158276,166398,'No data provided')
revenue_series = pd.Series(data=revenue_data_2021,index=month_index_2021)
print(type(revenue_series))

<class 'pandas.core.series.Series'>


In [ ]:
print(revenue_series)

Jan              212861
Feb              100372
Mar              128953
Apr              100163
May              208129
Jun              182944
Jul              236284
Aug              243133
Sep              198641
Oct              158276
Nov              166398
Dec    No data provided
dtype: object


In [ ]:
print(revenue_series['Dec'])

No data provided


In [ ]:
print(revenue_series[['Jan','Mar','Apr']])

Jan    212861
Mar    128953
Apr    100163
dtype: object


Dataframes

In [ ]:
row_labels = [0,1,2,3,4]
column_labels = ['A','B','C']
data = [[1,2,5],(4,2,4),{6,7,9},[3,2,4],[3,3,2]]

In [ ]:
df = pd.DataFrame(index=row_labels, data=data, columns=column_labels)
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
   A  B  C
0  1  2  5
1  4  2  4
2  9  6  7
3  3  2  4
4  3  3  2


In [ ]:
print(df.set_index('C'))

   A  B
C      
5  1  2
4  4  2
7  9  6
4  3  2
2  3  3


In [ ]:
print(df.set_index('C', drop=False))

   A  B  C
C         
5  1  2  5
4  4  2  4
7  9  6  7
4  3  2  4
2  3  3  2


In [ ]:
print(df.set_index('C', drop=False,inplace=True))

None


In [ ]:
print(df.set_index('B', drop=False,append=True))

     A  B  C
C B         
5 2  1  2  5
4 2  4  2  4
7 6  9  6  7
4 2  3  2  4
2 3  3  3  2


In [ ]:
df.reset_index(drop=True,inplace=True)
print(df)

   A  B  C
0  1  2  5
1  4  2  4
2  9  6  7
3  3  2  4
4  3  3  2


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
employees = ['employee1', '  employee2', 'employee3  ', 'employee4  ','employee5', 'employee6', 'employee7', 'employee8']
position = ['analyst', 'manager', 'analyst', 'analyst', 'manager','senior manager','manager',None]
salary = [30000,56000,28000,33000,60000,75000, None, None]
columns = ['employee', 'position', 'salary']

In [ ]:
df = pd.DataFrame(data = list(zip(employees, position, salary)), columns=columns)
print(df)
print(df['employee'])

      employee        position   salary
0    employee1         analyst  30000.0
1    employee2         manager  56000.0
2  employee3           analyst  28000.0
3  employee4           analyst  33000.0
4    employee5         manager  60000.0
5    employee6  senior manager  75000.0
6    employee7         manager      NaN
7    employee8            None      NaN
0      employee1
1      employee2
2    employee3  
3    employee4  
4      employee5
5      employee6
6      employee7
7      employee8
Name: employee, dtype: object


In [ ]:
df['employee'] = df['employee'].apply(lambda x: x.strip())
print(df)

    employee        position   salary
0  employee1         analyst  30000.0
1  employee2         manager  56000.0
2  employee3         analyst  28000.0
3  employee4         analyst  33000.0
4  employee5         manager  60000.0
5  employee6  senior manager  75000.0
6  employee7         manager      NaN
7  employee8            None      NaN


In [ ]:
print(df.isna())
df.dropna()
print(df)

   employee  position  salary
0     False     False   False
1     False     False   False
2     False     False   False
3     False     False   False
4     False     False   False
5     False     False   False
6     False     False    True
7     False      True    True
    employee        position   salary
0  employee1         analyst  30000.0
1  employee2         manager  56000.0
2  employee3         analyst  28000.0
3  employee4         analyst  33000.0
4  employee5         manager  60000.0
5  employee6  senior manager  75000.0
6  employee7         manager      NaN
7  employee8            None      NaN


In [ ]:
df.dropna(axis=1)
print(df)

    employee        position   salary
0  employee1         analyst  30000.0
1  employee2         manager  56000.0
2  employee3         analyst  28000.0
3  employee4         analyst  33000.0
4  employee5         manager  60000.0
5  employee6  senior manager  75000.0
6  employee7         manager      NaN
7  employee8            None      NaN


In [ ]:
df.dropna(axis=1, thresh=7)
print(df)

    employee        position   salary
0  employee1         analyst  30000.0
1  employee2         manager  56000.0
2  employee3         analyst  28000.0
3  employee4         analyst  33000.0
4  employee5         manager  60000.0
5  employee6  senior manager  75000.0
6  employee7         manager      NaN
7  employee8            None      NaN


In [ ]:
df = df.ffill()
df['salary'] = df['salary'].fillna(df['salary'].mean())
print(df)

    employee        position   salary
0  employee1         analyst  30000.0
1  employee2         manager  56000.0
2  employee3         analyst  28000.0
3  employee4         analyst  33000.0
4  employee5         manager  60000.0
5  employee6  senior manager  75000.0
6  employee7         manager  75000.0
7  employee8         manager  75000.0


Applying Functions

In [ ]:
def remove_pct(x):
    return x[:-1]

In [ ]:
remove_pct('17.80%')
print(countries_df['% of world'].apply(remove_pct))

0    17.80
1    17.50
2     4.20
3     3.42
4     2.84
5     2.70
6     2.67
7     2.17
8     1.84
9     1.59
Name: % of world, dtype: object


In [ ]:
print(countries_df['% of world'].apply(lambda x: x[:-1]))

0    17.80
1    17.50
2     4.20
3     3.42
4     2.84
5     2.70
6     2.67
7     2.17
8     1.84
9     1.59
Name: % of world, dtype: object


Rearranging Columns

In [55]:
countries_df['% of world'] = countries_df['% of world'].apply(lambda x: x[:-1])
print(countries_df)

   Rank         Country    Region  Population % of world  \
0     1           China      Asia  1412600000       17.8   
1     2           India      Asia  1386946912       17.5   
2     3   United States  Americas   333073186        4.2   
3     4    Indonesia[b]      Asia   271350000        3.4   
4     5        Pakistan      Asia   225200000        2.8   
5     6          Brazil  Americas   214231641        2.7   
6     7         Nigeria    Africa   211401000        2.6   
7     8      Bangladesh      Asia   172062576        2.1   
8     9       Russia[b]    Europe   146171015        1.8   
9    10          Mexico  Americas   126014024        1.5   

   Population (millions)           Country / Region  
0                1412.60               China / Asia  
1                1386.95               India / Asia  
2                 333.07   United States / Americas  
3                 271.35        Indonesia[b] / Asia  
4                 225.20            Pakistan / Asia  
5              

Convert to Float

In [56]:
countries_df['% of world'] = countries_df['% of world'].astype(float)
print(countries_df)

   Rank         Country    Region  Population  % of world  \
0     1           China      Asia  1412600000        17.8   
1     2           India      Asia  1386946912        17.5   
2     3   United States  Americas   333073186         4.2   
3     4    Indonesia[b]      Asia   271350000         3.4   
4     5        Pakistan      Asia   225200000         2.8   
5     6          Brazil  Americas   214231641         2.7   
6     7         Nigeria    Africa   211401000         2.6   
7     8      Bangladesh      Asia   172062576         2.1   
8     9       Russia[b]    Europe   146171015         1.8   
9    10          Mexico  Americas   126014024         1.5   

   Population (millions)           Country / Region  
0                1412.60               China / Asia  
1                1386.95               India / Asia  
2                 333.07   United States / Americas  
3                 271.35        Indonesia[b] / Asia  
4                 225.20            Pakistan / Asia  
5   

Adding New Column

In [57]:
countries_df['World Pop']=countries_df['Population']/(countries_df['% of world']/100)
print(countries_df)

   Rank         Country    Region  Population  % of world  \
0     1           China      Asia  1412600000        17.8   
1     2           India      Asia  1386946912        17.5   
2     3   United States  Americas   333073186         4.2   
3     4    Indonesia[b]      Asia   271350000         3.4   
4     5        Pakistan      Asia   225200000         2.8   
5     6          Brazil  Americas   214231641         2.7   
6     7         Nigeria    Africa   211401000         2.6   
7     8      Bangladesh      Asia   172062576         2.1   
8     9       Russia[b]    Europe   146171015         1.8   
9    10          Mexico  Americas   126014024         1.5   

   Population (millions)           Country / Region     World Pop  
0                1412.60               China / Asia  7.935955e+09  
1                1386.95               India / Asia  7.925411e+09  
2                 333.07   United States / Americas  7.930314e+09  
3                 271.35        Indonesia[b] / Asia  7.9